### Login as Omar
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "omar@test.com",
  "password": "123456"
}

### Login as Sara
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "sara@test.com",
  "password": "123456"
}

### Login as Admin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "123456"
}