@baseUrl = http://localhost:3000
@token = PASTE_CUSTOMER_TOKEN_HERE
@productId = PASTE_PRODUCT_ID_HERE
@orderId = PASTE_ORDER_ID_HERE
@reviewId = PASTE_REVIEW_ID_HERE

### Create Review
POST {{baseUrl}}/reviews
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "{{productId}}",
  "orderId": "{{orderId}}",
  "rating": 5,
  "comment": "Amazing phone"
}

### Update Review
PATCH {{baseUrl}}/reviews/{{reviewId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "rating": 4,
  "comment": "Updated review comment"
}